//! Integration tests for `envctl dashboard`. Drives the real binary against a
//! fixture `.meta.yaml`, asserting the read-only render, the `--json` plan shape,
//! and that a deploy DRY-RUN writes NO file (fail-closed default).
use std::path::PathBuf;
use std::process::Command;

fn bin() -> &'static str {
    env!("CARGO_BIN_EXE_envctl")
}

/// `envctl` loads a manifest dir at startup even for the read-only dashboard verb.
/// Point it at an existing (empty) dir so the binary starts; the dashboard path
/// never touches the registry.
fn cmd(manifest_dir: &std::path::Path) -> Command {
    let mut c = Command::new(bin());
    c.env("ENVCTL_MANIFEST_DIR", manifest_dir);
    c
}

/// Write a fixture `.meta.yaml` into a unique temp dir; return the dir.
fn fixture_dir() -> PathBuf {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("envctl-dash-it-{nanos}"));
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(
        dir.join(".meta.yaml"),
        r#"projects:
  meta_cli:
    repo: git@github.com:FlexNetOS/meta_cli.git
  envctl:
    repo: git@github.com:FlexNetOS/envctl.git
    tags: [tools/env]
"#,
    )
    .unwrap();
    dir
}

#[test]
fn render_to_stdout_is_valid_kdl() {
    let dir = fixture_dir();
    let out = cmd(&dir)
        .args(["dashboard", "--meta-file"])
        .arg(dir.join(".meta.yaml"))
        .output()
        .expect("run envctl");
    assert!(
        out.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let kdl = String::from_utf8(out.stdout).unwrap();
    assert!(kdl.starts_with("// Generated by envctl dashboard"));
    assert!(kdl.contains("layout {"));
    assert!(kdl.contains("tab name=\"mission-control\" focus=true"));
    assert!(kdl.contains("tab name=\"tools/env\""));
    assert!(kdl.contains("pane name=\"envctl\""));
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn json_emits_dashboard_plan() {
    let dir = fixture_dir();
    let out = cmd(&dir)
        .args(["dashboard", "--json", "--meta-file"])
        .arg(dir.join(".meta.yaml"))
        .output()
        .expect("run envctl");
    assert!(out.status.success());
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(v["name"], "mission-control");
    let tabs = v["tabs"].as_array().unwrap();
    // mission-control + meta-core + tools/env
    assert_eq!(tabs.len(), 3);
    assert_eq!(tabs[0]["name"], "mission-control");
    assert!(v["kdl"].as_str().unwrap().contains("layout {"));
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn deploy_dry_run_writes_no_file() {
    let dir = fixture_dir();
    // Redirect the deploy target into the fixture dir via XDG_CONFIG_HOME so the
    // test never touches the real ~/.config.
    let xdg = dir.join("xdg");
    let out = cmd(&dir)
        .args(["dashboard", "--deploy", "--meta-file"])
        .arg(dir.join(".meta.yaml"))
        .env("XDG_CONFIG_HOME", &xdg)
        .output()
        .expect("run envctl");
    assert!(
        out.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8(out.stdout).unwrap();
    assert!(
        stdout.contains("dry-run"),
        "expected dry-run note: {stdout}"
    );
    // The fail-closed default must NOT have written the layout.
    let target = xdg.join("yazelix/configs/zellij/layouts/mission-control.kdl");
    assert!(
        !target.exists(),
        "dry-run must not write {}",
        target.display()
    );
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn deploy_apply_writes_the_file() {
    let dir = fixture_dir();
    let xdg = dir.join("xdg");
    let out = cmd(&dir)
        .args(["dashboard", "--deploy", "--apply", "--meta-file"])
        .arg(dir.join(".meta.yaml"))
        .env("XDG_CONFIG_HOME", &xdg)
        .output()
        .expect("run envctl");
    assert!(
        out.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let target = xdg.join("yazelix/configs/zellij/layouts/mission-control.kdl");
    assert!(target.exists(), "apply must write {}", target.display());
    let written = std::fs::read_to_string(&target).unwrap();
    assert!(written.contains("Generated by envctl dashboard"));
    std::fs::remove_dir_all(&dir).ok();
}
