//! Phase 4 REGISTER. Synthesize the `components.d/<id>.toml` drop-in so a built
//! repo becomes a first-class managed component. Captures full provenance
//! (source/ref/sha/strategy/build_system/build_cmd/transform/artifacts), a
//! SHA-pinned rebuild-from-source `install` hook, a `verify`, and a `remove` that
//! excises ONLY our managed symlinks then drops the 0700 clone. The text is fed
//! into executor::add_repo's existing atomic temp+rename+backup writer (one code
//! path over components.d). For Refactor::Ai the rebuild REPLAYS the recorded SHA,
//! never re-drives the agent.

#[derive(Clone, Debug)]
pub struct RegisterSpec {
    pub id: String,
    pub slug: String,
    pub display_name: String,
    pub source: String,
    pub git_ref: Option<String>,
    pub resolved_sha: String,
    pub strategy_tag: String,
    pub build_system: String,
    pub build_cmd: String,
    pub transform: Option<String>,
    /// detect/verify primary binary (post-rename); falls back to `id`.
    pub primary_bin: Option<String>,
    pub verify_cmd: Option<String>,
    /// (install_name, path-relative-to-clone) so rebuild can relink artifacts.
    pub relinks: Vec<(String, String)>,
    /// absolute install targets (~/.local/bin/<name>) — provenance + remove list.
    pub installed_targets: Vec<String>,
}

impl RegisterSpec {
    fn primary(&self) -> String {
        self.primary_bin.clone().unwrap_or_else(|| self.id.clone())
    }
}

/// Synthesize the drop-in TOML. `id`/`slug` are validated slugs; every user string
/// is single-quoted for bash and the caller has pre-rejected `'''`.
pub fn synth_dropin(spec: &RegisterSpec) -> String {
    let id = &spec.id;
    let primary = spec.primary();
    let verify = spec
        .verify_cmd
        .clone()
        .filter(|s| !s.trim().is_empty())
        .unwrap_or_else(|| format!("command -v {primary} && {primary} --version"));
    let ref_disp = match &spec.git_ref {
        Some(r) if !r.is_empty() => r.clone(),
        _ => "(default branch)".to_string(),
    };
    let src_sq = sh_q(&spec.source);
    let sha = &spec.resolved_sha;

    let checkout = match &spec.git_ref {
        Some(r) if !r.is_empty() => format!(
            "git -C \"$SRC\" fetch origin {r} && git -C \"$SRC\" checkout {r}",
            r = sh_q(r)
        ),
        _ => format!(
            "git -C \"$SRC\" fetch --depth 1 origin {sha} && git -C \"$SRC\" checkout --detach {sha}"
        ),
    };
    let transform_step = match &spec.transform {
        Some(t) if spec.strategy_tag == "refactor:patch" => format!("# replay refactor:patch transform\n{t}\n"),
        _ => String::new(),
    };
    // AUDIT-FIX (blocker): the relink line interpolates name+rel into a shell
    // double-quoted string; an unsafe char ($ ` " \ newline / ..) would break out.
    // Only emit relinks whose name is a slug and whose rel path is a safe charset.
    let relink_lines: String = spec
        .relinks
        .iter()
        .filter(|(name, rel)| safe_name(name) && safe_rel(rel))
        .map(|(name, rel)| format!("ln -sfn \"$SRC/{rel}\" \"$HOME/.local/bin/{name}\""))
        .collect::<Vec<_>>()
        .join("\n");
    let excise: String = if spec.installed_targets.is_empty() {
        "true".into()
    } else {
        spec.installed_targets
            .iter()
            .map(|p| format!(
                "for t in {q}; do if [ -L \"$t\" ] && readlink \"$t\" | grep -q \"$STORE/{slug}\"; then rm -f \"$t\"; fi; done",
                q = sh_q(p),
                slug = spec.slug
            ))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let mut s = String::new();
    // provenance header
    s.push_str("# generated by `envctl add-repo` (Phase 4)\n");
    s.push_str(&format!("#   strategy      = {}\n", spec.strategy_tag));
    s.push_str(&format!("#   source        = {}\n", spec.source));
    s.push_str(&format!("#   ref           = {ref_disp}\n"));
    s.push_str(&format!("#   resolved_sha  = {sha}\n"));
    s.push_str(&format!("#   build_system  = {}\n", spec.build_system));
    s.push_str(&format!("#   build_cmd     = {}\n", spec.build_cmd));
    if let Some(t) = &spec.transform {
        s.push_str(&format!("#   transform     = {}\n", t.replace('\n', " / ")));
    }
    s.push_str(&format!("#   artifacts     = {}\n", spec.installed_targets.join(", ")));
    s.push('\n');

    s.push_str("[[component]]\n");
    s.push_str(&format!("id = \"{id}\"\n"));
    s.push_str(&format!("name = {}\n", toml_str(&spec.display_name)));
    s.push_str("description = \"\"\"\n");
    s.push_str("Built from source via envctl add-repo (build-from-source; only runs when named).\n");
    s.push_str(&format!(
        "strategy={} source={} ref={ref_disp} sha={sha} build_system={}\n",
        spec.strategy_tag, spec.source, spec.build_system
    ));
    s.push_str(&format!("artifacts={}\n", spec.installed_targets.join(" ")));
    s.push_str("\"\"\"\n\n");

    s.push_str("[component.detect]\nkind = \"command\"\ncommand = \"bash\"\n");
    s.push_str(&format!("args = [\"-lc\", {}]\n\n", toml_str(&format!("command -v {primary}"))));

    s.push_str("[component.install]\nkind = \"script\"\nlogin_shell = true\nscript = '''\n");
    s.push_str("set -euo pipefail\n");
    s.push_str("install -d -m 700 \"$HOME/.local/share/envctl/repos\"\n");
    s.push_str(&format!("SRC=\"$HOME/.local/share/envctl/repos/{}\"\n", spec.slug));
    s.push_str(&format!(
        "if [ -d \"$SRC/.git\" ]; then git -C \"$SRC\" remote set-url origin {src_sq} || true; else git clone {src_sq} \"$SRC\"; fi\n"
    ));
    s.push_str(&format!("{checkout}\n"));
    s.push_str("cd \"$SRC\"\n");
    if !transform_step.is_empty() {
        s.push_str(&transform_step);
    }
    s.push_str(&format!("{}\n", spec.build_cmd));
    s.push_str("install -d -m 755 \"$HOME/.local/bin\"\n");
    if !relink_lines.is_empty() {
        s.push_str(&relink_lines);
        s.push('\n');
    }
    s.push_str("'''\n\n");

    s.push_str("[component.verify]\nkind = \"command\"\ncommand = \"bash\"\n");
    s.push_str(&format!("args = [\"-lc\", {}]\n\n", toml_str(&verify)));

    s.push_str("[component.remove]\nkind = \"script\"\nlogin_shell = true\nscript = '''\n");
    s.push_str("set -u\n");
    s.push_str("STORE=\"$HOME/.local/share/envctl/repos\"\n");
    s.push_str(&excise);
    s.push('\n');
    s.push_str(&format!("rm -rf \"$STORE/{}\"\n", spec.slug));
    s.push_str("'''\n\n");

    s.push_str("[component.wiring]\npath_entries = [\"~/.local/bin\"]\n");
    s
}

fn sh_q(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// A safe install name (slug): bare, no shell metachars.
fn safe_name(s: &str) -> bool {
    !s.is_empty()
        && s.len() <= 64
        && !s.starts_with('-')
        && s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
}
/// A safe clone-relative path: no `..`, no shell metachars, no leading `-`.
fn safe_rel(s: &str) -> bool {
    !s.is_empty()
        && !s.contains("..")
        && !s.starts_with('-')
        && s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | '/'))
}

/// TOML basic-string for an args[] element.
fn toml_str(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}
